pagehelper:
  helperDialect: mysql # 分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。 你可以配置helperDialect属性来指定分页插件使用哪种方言。
  reasonable: true # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  supportMethodsArguments: true # 支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。 使用方法可以参考测试代码中的 com.github.pagehelper.test.basic 包下的 ArgumentsMapTest 和 ArgumentsObjTest。


server:
  port: 8888
spring:
  #security:
  # user:
  #   name: admin
  #  password: a
  # roles:
  #  - USER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: a
    url: jdbc:mysql://localhost:3306/bbnmd?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
  application:
    name: microservice-provider-bbnmd   #应用服务名
mybatis:
  configuration:
    map-underscore-to-camel-case: true    #将_转为驼峰命名
mapper:
  identity: MYSQL   # 标识列用mysql  配置主键自动增长
logging:
  level:
    com.yc.piclib: debug

eureka:
  client:
    service-url:
      defaultZone: http://admin:a@eureka1:7301/eureka
  instance:
    instance-id: microservice-provider-bbnmd_1   #实例名
    lease-expiration-duration-in-seconds: 90  #如果现在超过了5s的时间间隔( default: 90 s )
    lease-renewal-interval-in-seconds: 30   #设置心跳的时间间隔( default:30s )


#监控配置
info:
  app.name: MICROSERVICE-PICLIB
  company.name: yc
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
  version: $project.version$

management:
  endpoints:
    web:
      exposure:
        include: '*'

