server:
  port: 7101
eureka:
  instance:
    hostname: EurekaForHighConfig
  client:
    fetch-registry: false #是否要从注册中心获取注册信息 , 解决eureka启动时报错
    register-with-eureka: false #是否将自生注册到eureka上
    service-url:
      defaultZone: http://admin:a@${eureka.instance.hostname}:${server.port}/eureka
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，ms (默认是60秒）
    enable-self-preservation: false       #设置为false表示关闭保护模式,在保护模式下，如因为网络或其它问题服务提供者掉线的话，eureka不会立即清空服务列表.
spring:
  security:
    user:
      name: admin
      password: a

application:
  name: microservice-ha-config-eureka